### ISSUE TITLE
Please push a new release to gradle/maven

### ISSUE THREAD

**Issue by tcortega** [Rebirth-Project/ufo-event-bus#1]
The latest version published is the 1.0.0 from November, 2022.

**Comment by patton73** [comment]
Basically there are no fixes or new added features from latest release. So i will close this bug.
Thanks a lot for your interest in the project.
If you have bugs to report. Please do it. We will fix asap and the release a new version.
Andrea.

**Comment by patton73** [comment]
Yes at least we can release a new minor version since some modifications on internal architecture were made.

**Comment by patton73** [comment]
A new release 1.0.1 is available.
